# Generated by Django 2.2.2 on 2019-09-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('title_id', models.CharField(max_length=10)),
                ('example_id', models.CharField(max_length=10)),
                ('select_id', models.CharField(max_length=10)),
                ('check_yn', models.CharField(max_length=1)),
            ],
        ),
    ]
