# Generated by Django 2.2.2 on 2019-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='solveC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('login_time', models.DateTimeField()),
                ('user_name', models.CharField(max_length=255)),
                ('example_id', models.CharField(max_length=10)),
                ('check_YN', models.CharField(max_length=1)),
            ],
        ),
    ]
