# Generated by Django 2.2.2 on 2019-08-16 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20190816_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='solveC',
            new_name='solve',
        ),
    ]
