# Generated by Django 2.2.2 on 2019-08-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20190816_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('example_id', models.CharField(max_length=10)),
                ('select_id', models.CharField(max_length=10)),
                ('check', models.CharField(max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='solve',
        ),
    ]
