# Generated by Django 2.2.2 on 2019-08-17 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_result_title_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='check',
            new_name='check_yn',
        ),
    ]
