# Generated by Django 2.2.2 on 2019-12-06 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='current_price',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
