# Generated by Django 3.0 on 2019-12-09 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stocks_stock_returns'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
