# Generated by Django 3.0 on 2019-12-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stocks_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='update_date',
            field=models.DateTimeField(max_length=255, null=True),
        ),
    ]
