# Generated by Django 2.2.2 on 2019-09-03 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190903_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='recommend',
        ),
    ]
