# Generated by Django 2.2.2 on 2019-09-04 06:21

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_board_recommend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
