# Generated by Django 2.2.2 on 2019-09-04 07:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20190904_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='modify_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='write_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
