# Generated by Django 2.2.2 on 2019-11-19 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20190904_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='enable_yn',
            field=models.CharField(default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
