# Generated by Django 2.2.2 on 2019-11-28 06:47

import ckeditor_uploader.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20191119_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
